### PR TITLE
FS GB Tools

### PR DESCRIPTION
**Pull request by stuartshields**
@mattheu  I've created this PR/Branch as it incorporates #22 and #28 which are both needed for a project.

### CODE REVIEW

**Comment by mattheu** [comment]
Closing this branch as its now out fairly out of date.

APologies that there has been so many changes - its been a pain trying to keep up with the pace of development in core! This should stop now 5.0 has landed.

**Comment by tareiking** [comment]
@mattheu - we are still using `fs-gb-tools` branch currently and subsequently, it's a dependency for us.

I've restored the branch and will fork these changes over to another repo early next week to remove the dependency.

**Comment by mattheu** [comment]
OK thats fine we can keep the branch around for legacy reasons.

Have you done much customisations? It shouldn't be too hard to update this and will probably be necessary once you update to WP 5.0. I'd be interested to hear whether this goes smoothly - happy to help out if you run into issues.

**Comment by tareiking** [comment]
Thanks @mattheu - I've added branch protection for that `fs-gb-tools` branch.

I'm honestly not aware how many changes this branch has done, but we do have quite the big gutenberg update plan in place for said project, so I'll happily report things back when we kick that migration off! Appreciate the offer for an assist too ❤️

**Pull request closed without merging**
